apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.issuer }}
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ template "fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.externalPort }}