// ORDERS
export const SET_LIVRO_ORDENS = 'SET_LIVRO_ORDENS';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_TICKER_SUCCESS = 'FETCH_TICKER_SUCCESS';
export const FETCH_TRADES_SUCCESS = 'FETCH_TRADES_SUCCESS';
export const CHANGE_CURRENT_PAIR = 'CHANGE_CURRENT_PAIR';
export const FETCH_AVAILABLE_PAIRS_SUCCESS = 'FETCH_AVAILABLE_PAIRS_SUCCESS';
export const SET_LIVRO_ORDENS_ACUMULADO = 'SET_LIVRO_ORDENS_ACUMULADO';
export const UPDATE_BOX_TRADE = 'UPDATE_BOX_TRADE';
export const FETCH_ORDER_LIMITS_SUCCESS = 'FETCH_ORDER_LIMITS_SUCCESS';

// USERS
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_MY_BALANCE = 'FETCH_MY_BALANCE';
export const FETCH_DEPOSIT_ADDRESS_SUCCESS = 'FETCH_DEPOSIT_ADDRESS_SUCCESS';
export const FETCH_USER_EXTRACT_SUCCESS = 'FETCH_USER_EXTRACT_SUCCESS';
export const FETCH_DEPOSITS_SUCCESS = 'FETCH_DEPOSITS_SUCCESS';
export const UPDATE_USER_PREFERENCE = 'UPDATE_USER_PREFERENCE';
export const FETCH_VERIFICATIONS_SUCCESS = 'FETCH_VERIFICATIONS_SUCCESS';
export const FETCH_LOGIN_HISTORY_SUCCESS = 'FETCH_LOGIN_HISTORY_SUCCESS';
export const FETCH_SELFIE_TOKEN_SUCCESS = 'FETCH_SELFIE_TOKEN_SUCCESS';
export const HAS_USER_LOGOUT = 'HAS_USER_LOGOUT';
export const FETCH_LIMIT_SUCCESS = 'FETCH_LIMIT_SUCCESS';
export const IS_LIMIT_FETCHING = 'IS_LIMIT_FETCHING';

// BANK
export const FETCH_BANK_ACCOUNTS_SUCCESS = 'FETCH_BANK_ACCOUNTS_SUCCESS';
export const FETCH_LOCAL_BANKS_SUCCESS = 'FETCH_LOCAL_BANKS_SUCCESS';

// AUTH
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
